### ISSUE TITLE
AmazonProduct won't parse Relationships

### ISSUE THREAD

**Issue by HMAZonderland** [CPIGroup/phpAmazonMWS#51]
I've figured that the Relationships node of the Xml for `GetMatchingProductForIdResponse` aren't getting parsed by the function. This has to do with the fact that it uses namespaced child nodes combined with non-namespaced child nodes. It seems the SimepleXml lib cannot handle the the non-namespaced nodes. For instance, it is not possible getting the `Identifiers` node.
```php
//Relationships
if ($xml->Relationships){
    foreach($xml->Relationships->children() as $x){
        foreach($x->children() as $y){
            foreach($y->children() as $z){
                foreach($z->children() as $zzz){
                    $this->data['Relationships'][$x->getName()][$y->getName()][$z->getName()][$zzz->getName()] = (string)$zzz;
                }
            }
        }
    }
}
```

```xml
<?xml version="1.0"?>
<GetMatchingProductForIdResponse xmlns="http://mws.amazonservices.com/schema/Products/2011-10-01">
    <GetMatchingProductForIdResult Id="1554" IdType="SellerSKU" status="Success">
        <Products xmlns="http://mws.amazonservices.com/schema/Products/2011-10-01" xmlns:ns2="http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd">
            <Product>
                <Identifiers>
                    <MarketplaceASIN>
                        <MarketplaceId>A1PA6795UKMFR9</MarketplaceId>
                        <ASIN>B00XQACUYU</ASIN>
                    </MarketplaceASIN>
                </Identifiers>
                <AttributeSets>
                    <ns2:ItemAttributes xml:lang="de-DE">
                        <ns2:Binding>Textilien</ns2:Binding>
                        <ns2:Brand>Mim-Pi</ns2:Brand>
                        <ns2:Department>Mädchen</ns2:Department>
                        <ns2:NumberOfItems>1</ns2:NumberOfItems>
                        <ns2:PackageQuantity>1</ns2:PackageQuantity>
                        <ns2:ProductGroup>Apparel</ns2:ProductGroup>
                        <ns2:ProductTypeName>PANTS</ns2:ProductTypeName>
                        <ns2:SmallImage>
                            <ns2:URL>http://ecx.images-amazon.com/images/I/41OMIkqP2IL._SL75_.jpg</ns2:URL>
                            <ns2:Height Units="pixels">75</ns2:Height>
                            <ns2:Width Units="pixels">75</ns2:Width>
                        </ns2:SmallImage>
                        <ns2:Title>MIM-PI Baggy Mädchen Hose</ns2:Title>
                    </ns2:ItemAttributes>
                </AttributeSets>
                <Relationships>
                    <ns2:VariationChild>
                        <Identifiers>
                            <MarketplaceASIN>
                                <MarketplaceId>A1PA6795UKMFR9</MarketplaceId>
                                <ASIN>B00XQACWXO</ASIN>
                            </MarketplaceASIN>
                        </Identifiers>
                        <ns2:Color>Blau</ns2:Color>
                        <ns2:Size>92</ns2:Size>
                    </ns2:VariationChild>
                    <ns2:VariationChild>
                        <Identifiers>
                            <MarketplaceASIN>
                                <MarketplaceId>A1PA6795UKMFR9</MarketplaceId>
                                <ASIN>B00XQACZRW</ASIN>
                            </MarketplaceASIN>
                        </Identifiers>
                        <ns2:Color>Blau</ns2:Color>
                        <ns2:Size>98</ns2:Size>
                    </ns2:VariationChild>
                    <ns2:VariationChild>
                        <Identifiers>
                            <MarketplaceASIN>
                                <MarketplaceId>A1PA6795UKMFR9</MarketplaceId>
                                <ASIN>B00XQAD2HO</ASIN>
                            </MarketplaceASIN>
                        </Identifiers>
                        <ns2:Color>Blau</ns2:Color>
                        <ns2:Size>104</ns2:Size>
                    </ns2:VariationChild>
                    <ns2:VariationChild>
                        <Identifiers>
                            <MarketplaceASIN>
                                <MarketplaceId>A1PA6795UKMFR9</MarketplaceId>
                                <ASIN>B00XQAD59Y</ASIN>
                            </MarketplaceASIN>
                        </Identifiers>
                        <ns2:Color>Blau</ns2:Color>
                        <ns2:Size>110</ns2:Size>
                    </ns2:VariationChild>
                    <ns2:VariationChild>
                        <Identifiers>
                            <MarketplaceASIN>
                                <MarketplaceId>A1PA6795UKMFR9</MarketplaceId>
                                <ASIN>B00XQAD8LY</ASIN>
                            </MarketplaceASIN>
                        </Identifiers>
                        <ns2:Color>Blau</ns2:Color>
                        <ns2:Size>116</ns2:Size>
                    </ns2:VariationChild>
                    <ns2:VariationChild>
                        <Identifiers>
                            <MarketplaceASIN>
                                <MarketplaceId>A1PA6795UKMFR9</MarketplaceId>
                                <ASIN>B00XQADAKI</ASIN>
                            </MarketplaceASIN>
                        </Identifiers>
                        <ns2:Color>Blau</ns2:Color>
                        <ns2:Size>122</ns2:Size>
                    </ns2:VariationChild>
                    <ns2:VariationChild>
                        <Identifiers>
                            <MarketplaceASIN>
                                <MarketplaceId>A1PA6795UKMFR9</MarketplaceId>
                                <ASIN>B00XQADDYG</ASIN>
                            </MarketplaceASIN>
                        </Identifiers>
                        <ns2:Color>Blau</ns2:Color>
                        <ns2:Size>128</ns2:Size>
                    </ns2:VariationChild>
                    <ns2:VariationChild>
                        <Identifiers>
                            <MarketplaceASIN>
                                <MarketplaceId>A1PA6795UKMFR9</MarketplaceId>
                                <ASIN>B00XQADGWA</ASIN>
                            </MarketplaceASIN>
                        </Identifiers>
                        <ns2:Color>Blau</ns2:Color>
                        <ns2:Size>134</ns2:Size>
                    </ns2:VariationChild>
                    <ns2:VariationChild>
                        <Identifiers>
                            <MarketplaceASIN>
                                <MarketplaceId>A1PA6795UKMFR9</MarketplaceId>
                                <ASIN>B00XQADJV8</ASIN>
                            </MarketplaceASIN>
                        </Identifiers>
                        <ns2:Color>Blau</ns2:Color>
                        <ns2:Size>140</ns2:Size>
                    </ns2:VariationChild>
                    <ns2:VariationChild>
                        <Identifiers>
                            <MarketplaceASIN>
                                <MarketplaceId>A1PA6795UKMFR9</MarketplaceId>
                                <ASIN>B00XQADN7I</ASIN>
                            </MarketplaceASIN>
                        </Identifiers>
                        <ns2:Color>Blau</ns2:Color>
                        <ns2:Size>146</ns2:Size>
                    </ns2:VariationChild>
                    <ns2:VariationChild>
                        <Identifiers>
                            <MarketplaceASIN>
                                <MarketplaceId>A1PA6795UKMFR9</MarketplaceId>
                                <ASIN>B00XQADPXA</ASIN>
                            </MarketplaceASIN>
                        </Identifiers>
                        <ns2:Color>Blau</ns2:Color>
                        <ns2:Size>152</ns2:Size>
                    </ns2:VariationChild>
                </Relationships>
                <SalesRankings/>
            </Product>
        </Products>
    </GetMatchingProductForIdResult>
    <GetMatchingProductForIdResult Id="1556" IdType="SellerSKU" status="Success">
        <Products xmlns="http://mws.amazonservices.com/schema/Products/2011-10-01" xmlns:ns2="http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd">
            <Product>
                <Identifiers>
                    <MarketplaceASIN>
                        <MarketplaceId>A1PA6795UKMFR9</MarketplaceId>
                        <ASIN>B00XQ9OE8G</ASIN>
                    </MarketplaceASIN>
                </Identifiers>
                <AttributeSets>
                    <ns2:ItemAttributes xml:lang="de-DE">
                        <ns2:Binding>Textilien</ns2:Binding>
                        <ns2:Brand>Mim-Pi</ns2:Brand>
                        <ns2:Department>Mädchen</ns2:Department>
                        <ns2:NumberOfItems>1</ns2:NumberOfItems>
                        <ns2:PackageQuantity>1</ns2:PackageQuantity>
                        <ns2:ProductGroup>Apparel</ns2:ProductGroup>
                        <ns2:ProductTypeName>SHIRT</ns2:ProductTypeName>
                        <ns2:SmallImage>
                            <ns2:URL>http://ecx.images-amazon.com/images/I/41zzIcFZetL._SL75_.jpg</ns2:URL>
                            <ns2:Height Units="pixels">75</ns2:Height>
                            <ns2:Width Units="pixels">75</ns2:Width>
                        </ns2:SmallImage>
                        <ns2:Title>MIM-PI Mädchen T-shirt</ns2:Title>
                    </ns2:ItemAttributes>
                </AttributeSets>
                <Relationships>
                    <ns2:VariationChild>
                        <Identifiers>
                            <MarketplaceASIN>
                                <MarketplaceId>A1PA6795UKMFR9</MarketplaceId>
                                <ASIN>B00XQ9OFRG</ASIN>
                            </MarketplaceASIN>
                        </Identifiers>
                        <ns2:Color>Blau</ns2:Color>
                        <ns2:Size>92</ns2:Size>
                    </ns2:VariationChild>
                    <ns2:VariationChild>
                        <Identifiers>
                            <MarketplaceASIN>
                                <MarketplaceId>A1PA6795UKMFR9</MarketplaceId>
                                <ASIN>B00XQ9OI6O</ASIN>
                            </MarketplaceASIN>
                        </Identifiers>
                        <ns2:Color>Blau</ns2:Color>
                        <ns2:Size>98</ns2:Size>
                    </ns2:VariationChild>
                    <ns2:VariationChild>
                        <Identifiers>
                            <MarketplaceASIN>
                                <MarketplaceId>A1PA6795UKMFR9</MarketplaceId>
                                <ASIN>B00XQ9OK9O</ASIN>
                            </MarketplaceASIN>
                        </Identifiers>
                        <ns2:Color>Blau</ns2:Color>
                        <ns2:Size>104</ns2:Size>
                    </ns2:VariationChild>
                    <ns2:VariationChild>
                        <Identifiers>
                            <MarketplaceASIN>
                                <MarketplaceId>A1PA6795UKMFR9</MarketplaceId>
                                <ASIN>B00XQ9OMU6</ASIN>
                            </MarketplaceASIN>
                        </Identifiers>
                        <ns2:Color>Blau</ns2:Color>
                        <ns2:Size>110</ns2:Size>
                    </ns2:VariationChild>
                    <ns2:VariationChild>
                        <Identifiers>
                            <MarketplaceASIN>
                                <MarketplaceId>A1PA6795UKMFR9</MarketplaceId>
                                <ASIN>B00XQ9OPF8</ASIN>
                            </MarketplaceASIN>
                        </Identifiers>
                        <ns2:Color>Blau</ns2:Color>
                        <ns2:Size>116</ns2:Size>
                    </ns2:VariationChild>
                    <ns2:VariationChild>
                        <Identifiers>
                            <MarketplaceASIN>
                                <MarketplaceId>A1PA6795UKMFR9</MarketplaceId>
                                <ASIN>B00XQ9ORMO</ASIN>
                            </MarketplaceASIN>
                        </Identifiers>
                        <ns2:Color>Blau</ns2:Color>
                        <ns2:Size>122</ns2:Size>
                    </ns2:VariationChild>
                    <ns2:VariationChild>
                        <Identifiers>
                            <MarketplaceASIN>
                                <MarketplaceId>A1PA6795UKMFR9</MarketplaceId>
                                <ASIN>B00XQ9OU3K</ASIN>
                            </MarketplaceASIN>
                        </Identifiers>
                        <ns2:Color>Blau</ns2:Color>
                        <ns2:Size>128</ns2:Size>
                    </ns2:VariationChild>
                    <ns2:VariationChild>
                        <Identifiers>
                            <MarketplaceASIN>
                                <MarketplaceId>A1PA6795UKMFR9</MarketplaceId>
                                <ASIN>B00XQ9OW1U</ASIN>
                            </MarketplaceASIN>
                        </Identifiers>
                        <ns2:Color>Blau</ns2:Color>
                        <ns2:Size>134</ns2:Size>
                    </ns2:VariationChild>
                    <ns2:VariationChild>
                        <Identifiers>
                            <MarketplaceASIN>
                                <MarketplaceId>A1PA6795UKMFR9</MarketplaceId>
                                <ASIN>B00XQ9OYC2</ASIN>
                            </MarketplaceASIN>
                        </Identifiers>
                        <ns2:Color>Blau</ns2:Color>
                        <ns2:Size>140</ns2:Size>
                    </ns2:VariationChild>
                </Relationships>
                <SalesRankings/>
            </Product>
        </Products>
    </GetMatchingProductForIdResult>
    <ResponseMetadata>
        <RequestId>5b394041-ba9c-4630-b948-c2c98ca626d8</RequestId>
    </ResponseMetadata>
</GetMatchingProductForIdResponse>
```

**Comment by HMAZonderland** [comment]
Im not sure this code would do;
```php
if ($xml->Relationships){
    foreach($xml->Relationships->children() as $x){
        foreach($x->children() as $y){
            foreach($y->children() as $z){
                foreach($z->children() as $zzz){
                    $this->data['Relationships'][$x->getName()][$y->getName()][$z->getName()][$zzz->getName()] = (string)$zzz;
                }
            }
        }
    }
}
```

But this made my Xml work:
```php
if ($xml->Relationships) {
    foreach($xml->Relationships->children('ns2', true) as $variation) {
        foreach ($variation->children() as $identifier) {
            $this->data['Relationships'][] = [
                'ASIN' => (string) $identifier->MarketplaceASIN->ASIN,
                'Color' => (string) $variation->Color,
                'Size' => (int) $variation->Size
            ];
        }
    }
}
```

**Comment by Peardian** [comment]
Yes, this is an issue that was discovered in February and fixed in the master development branch. (https://github.com/CPIGroup/phpAmazonMWS/commit/e93aa29c2569f2d31a708a42365ad60e535551c7)

**Comment by HMAZonderland** [comment]
When are you releasing a new version (composer)?

**Comment by Peardian** [comment]
As soon as I am allowed to do so.

**Comment by HMAZonderland** [comment]
Just checked. This fix doesn't completely fix the problem. I do not receive all the Relationship values / ASIN's with the test Xml from my first post. I actually receive 1 of 10 ASIN's in the Relationship VariationChild.

**Comment by Peardian** [comment]
I think I see why. All ten of those nodes use the same name, so it's overwriting the same "VariationChild" key in the array every time, isn't it? Unfortunately, I am not able to look into it or fix it at this time.

**Comment by HMAZonderland** [comment]
Since the ASIN / Marketplace combination is linked to the Variation data, add them to an array Relationships? Something like:

```php
[Relationships] => Array
    (
        [0] => Array
        (
            ASIN => '123'
            MarketplaceId => '123
            W => 'X'
            Y => 'Z'
        )
)
```

**Comment by HMAZonderland** [comment]
Do you have more test data, other than my example?

**Comment by Peardian** [comment]
I was thinking that the variation data should be stored as an array, yes. However, I'd have to look into it more to see in what ways the data can be condensed, if at all.

And no, I'm afraid I don't have any test data on hand.

**Comment by HMAZonderland** [comment]
How about this?
```php
//Relationships
if ($xml->Relationships){
    //child relations use namespace but parent does not
    foreach($xml->Relationships->children('ns2', true) as $variation){
        $variations = (array) $variation;
        foreach($variation->children() as $identifier) {
            $this->data['Relationships'][] = array_merge($variations, [
                'ASIN' => (string) $identifier->MarketplaceASIN->ASIN,
                'MarketplaceId' => (string) $identifier->MarketplaceASIN->MarketplaceId
            ]);
        }
    }
}
```

Will include the VariationData (of any name / type) into the array. Based upon my test data, this will output::
```php
[Relationships] => Array
(
        [0] => Array
        (
                [Color] => Blau
                [Size] => 92
                [ASIN] => B00XQACWXO
                [MarketplaceId] => A1PA6795UKMFR9
        )
        [1] => Array
        (
                [Color] => Blau
                [Size] => 98
                [ASIN] => B00XQACZRW
                [MarketplaceId] => A1PA6795UKMFR9
        )
        [2] => Array
        (
                [Color] => Blau
                [Size] => 104
                [ASIN] => B00XQAD2HO
                [MarketplaceId] => A1PA6795UKMFR9
        )
        [3] => Array
        (
                [Color] => Blau
                [Size] => 110
                [ASIN] => B00XQAD59Y
                [MarketplaceId] => A1PA6795UKMFR9
        )
        [4] => Array
        (
                [Color] => Blau
                [Size] => 116
                [ASIN] => B00XQAD8LY
                [MarketplaceId] => A1PA6795UKMFR9
        )
        [5] => Array
        (
                [Color] => Blau
                [Size] => 122
                [ASIN] => B00XQADAKI
                [MarketplaceId] => A1PA6795UKMFR9
        )
        [6] => Array
        (
                [Color] => Blau
                [Size] => 128
                [ASIN] => B00XQADDYG
                [MarketplaceId] => A1PA6795UKMFR9
        )
        [7] => Array
        (
                [Color] => Blau
                [Size] => 134
                [ASIN] => B00XQADGWA
                [MarketplaceId] => A1PA6795UKMFR9
        )
        [8] => Array
        (
                [Color] => Blau
                [Size] => 140
                [ASIN] => B00XQADJV8
                [MarketplaceId] => A1PA6795UKMFR9
        )
        [9] => Array
        (
                [Color] => Blau
                [Size] => 146
                [ASIN] => B00XQADN7I
                [MarketplaceId] => A1PA6795UKMFR9
        )
        [10] => Array
        (
                [Color] => Blau
                [Size] => 152
                [ASIN] => B00XQADPXA
                [MarketplaceId] => A1PA6795UKMFR9
        )
)
```

**Comment by Peardian** [comment]
It looks like that gets all the data from your sample, but I would have to research it further to see if the solution works for all possible responses. Variations is the one area of products that I do not have much familiarity with, because the stores I work with don't use that feature yet.

**Comment by HMAZonderland** [comment]
I did not edit any other line of code, except for that one. Perhaps run your PHPUnit with my edits? Would be nice having the Xsd on this one. :disappointed:

**Comment by Peardian** [comment]
What I mean is that I can't research or test it at all right now. Just running the tests won't be enough, because the test data is not comprehensive and the tests pass even before the namespace issue was (partially) fixed before.

You should be able to find the XSD somewhere. The XML you posted up above links to an XSD, but the link doesn't seem to work. I do not have it myself, unfortunately.

**Comment by HMAZonderland** [comment]
I cannot find the XSD either. So its impossible for me to validate and/or create a good testcase. 

Where are we moving from here? Do I have to fork this project with my edits just to keep my project running? Because my project relies heavily on this small piece of code.

**Comment by HMAZonderland** [comment]
Did some further testing when requesting by EAN (see Xml). Which changed the function again. It could happen that there are no VariationChild nodes. So I updated to function to this: 
```php
//Relationships
if ($xml->Relationships){
    // When there are variations (VariationChild) nodes
    foreach($xml->Relationships->children('ns2', true) as $variation){
        $variations = (array) $variation;
        foreach($variation->children() as $identifier) {
            $this->data['Relationships'][] = array_merge($variations, (array) $identifier->MarketplaceASIN);
        }
    }

    // when there isn't any VariationChild node, but there are identifiers
    foreach ($xml->Relationships->children() as $identifier) {
        $this->data['Relationships'][] = (array) $identifier->Identifiers->MarketplaceASIN;
    }
}
```
Xml:
```xml
<?xml version="1.0"?>
<GetMatchingProductForIdResponse xmlns="http://mws.amazonservices.com/schema/Products/2011-10-01">
    <GetMatchingProductForIdResult Id="8718888013105" IdType="EAN" status="Success">
        <Products xmlns="http://mws.amazonservices.com/schema/Products/2011-10-01" xmlns:ns2="http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd">
            <Product>
                <Identifiers>
                    <MarketplaceASIN>
                        <MarketplaceId>A1PA6795UKMFR9</MarketplaceId>
                        <ASIN>B00V38Q1DI</ASIN>
                    </MarketplaceASIN>
                </Identifiers>
                <AttributeSets>
                    <ns2:ItemAttributes xml:lang="de-DE">
                        <ns2:Binding>Textilien</ns2:Binding>
                        <ns2:Brand>Mim-Pi</ns2:Brand>
                        <ns2:Color>Grau</ns2:Color>
                        <ns2:Department>Mädchen</ns2:Department>
                        <ns2:PartNumber>0115S-1513</ns2:PartNumber>
                        <ns2:ProductGroup>Apparel</ns2:ProductGroup>
                        <ns2:ProductTypeName>SWEATER</ns2:ProductTypeName>
                        <ns2:Size>122</ns2:Size>
                        <ns2:SmallImage>
                            <ns2:URL>http://ecx.images-amazon.com/images/I/417RrUuX3rL._SL75_.jpg</ns2:URL>
                            <ns2:Height Units="pixels">49</ns2:Height>
                            <ns2:Width Units="pixels">75</ns2:Width>
                        </ns2:SmallImage>
                        <ns2:Title>Mim-Pi Sweat Cardigan mim1513, Größe:122</ns2:Title>
                    </ns2:ItemAttributes>
                </AttributeSets>
                <Relationships>
                    <VariationParent>
                        <Identifiers>
                            <MarketplaceASIN>
                                <MarketplaceId>A1PA6795UKMFR9</MarketplaceId>
                                <ASIN>B00V3850SA</ASIN>
                            </MarketplaceASIN>
                        </Identifiers>
                    </VariationParent>
                </Relationships>
                <SalesRankings/>
            </Product>
        </Products>
    </GetMatchingProductForIdResult>
    <ResponseMetadata>
        <RequestId>bc979b82-9c14-41f0-816b-9813de3461d6</RequestId>
    </ResponseMetadata>
</GetMatchingProductForIdResponse>
```

**Comment by Peardian** [comment]
If you need the changes, then yes, you can fork it and put the changes on it for now, because it could be a while before I am able to look into it myself.

**Comment by Peardian** [comment]
Finally taken care of
